@baseUrl = http://localhost:8000/
@token_1 = 2e2e3f3f96e5784cd8f43f1a0063fad1f0eabf24
@token_2 = 96e5a312367a4b2b43d9467728ffd88c447f29e5
POST {{baseUrl}}user/register
Content-Type: application/json

{
    "username": "jerry",
    "password": "123412fg",
    "email": "gerry@gmail.com",
    "type": "buyer"
}
###
POST {{baseUrl}}user/register
Content-Type: application/json

{
    "username": "jerry_1",
    "password": "123412fg",
    "email": "gerry_1@gmail.com",
    "type": "shop"
}
###
POST {{baseUrl}}user/register
Content-Type: application/json

{
    "username": "jerry_3",
    "password": "123412fg",
    "email": "mr.john.milton@yandex.ru"
}
###
POST {{baseUrl}}user/login
Content-Type: application/json

{
    // "username": "jerry",
    "email": "mr.john.milton@mail.ru",
    "password": "123412fg"
}
###
POST {{baseUrl}}user/login
Content-Type: application/json

{
    // "username": "jerry",
    "email": "gerry_1@gmail.com",
    "password": "123412fg"
}
###
GET {{baseUrl}}user
Content-Type: application/json
Authorization: Token {{token_1}}

###
PATCH {{baseUrl}}user
Content-Type: application/json
Authorization: Token {{token_1}}

{
    // "username": "jerry_2",
    // "type": "shop",
    // "password": "1234123ff"
    "email": "mr.john@yandex.ru"
}
###
POST {{baseUrl}}partner/update
Content-Type: application/json
Authorization: Token {{token_2}}

{
    "file": "/home/jerry/netology_hw/netology_dplm/data/shop_1.yaml"
}
###
GET {{baseUrl}}categories
Content-Type: application/json
# Authorization: 
###
GET {{baseUrl}}shops
Content-Type: application/json
###
GET {{baseUrl}}products?search=
###
GET {{baseUrl}}basket
Content-Type: application/json
Authorization: Token {{token_1}}
###
POST {{baseUrl}}basket
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "items": [
        {
            "product_info": 5,
            "quantity": 2
        },
        {
            "product_info": 6,
            "quantity": 1
        }
    ]
}
###
PUT {{baseUrl}}basket
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "id": 7,
    "items": [
        {
            "product_info": 3,
            "quantity": 3
        }
    ]
}
###
DELETE {{baseUrl}}basket
Content-Type: application/json
Authorization: Token {{token_1}}
###
GET {{baseUrl}}partner/status
Content-Type: application/json
Authorization: Token {{token_2}}
###
POST {{baseUrl}}partner/status
Content-Type: application/json
Authorization: Token {{token_2}}

{
    "status": "True"
}
###
GET {{baseUrl}}partner/orders
Content-Type: application/json
Authorization: Token {{token_2}}
###
GET {{baseUrl}}user/contact
Content-Type: application/json
Authorization: Token {{token_1}}
###
POST {{baseUrl}}user/contact
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "type": "address",
    "value": "Moscow, Mayakovsky st., 12a"
}
###
PUT {{baseUrl}}user/contact
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "id": 1,
    "type": "email",
    "value": "jerry_put@gmail.com"
}
###
DELETE {{baseUrl}}user/contact
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "id": 1
}
###
GET {{baseUrl}}order
Content-Type: application/json
Authorization: Token {{token_1}}
###
POST {{baseUrl}}order
Content-Type: application/json
Authorization: Token {{token_1}}

{
    "id": 10
}
###
POST {{baseUrl}}user/password/reset
Content-Type: application/json
# Authorization: Token {{token_1}}

{
    "email": "mr.john.milton@yandex.ru"
}
###
POST {{baseUrl}}user/password/reset/confirm
Content-Type: application/json
# Authorization: Token {{token_1}}

{
    "token": "Token",
    "password": "example"
}
