# Generated by Django 4.2 on 2023-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='extertal_id',
            new_name='external_id',
        ),
    ]
